name = "Cobblemon Dist"
author = "Fett"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19c2445de7db0610769719a281be7b77c9db8f722e2f491a854a44ff0baafa7f"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
