name = "Cobblemon Dist"
author = "Fett"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80c0a9ccdea2362f27ba74025f03fbbf1221f4ca143d2c303bdf363330102152"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
